# Generated by Django 4.1 on 2024-08-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='LinkMapping',
        ),
    ]
