# Generated by Django 5.1 on 2024-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_question_linkmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmapping',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='linkmapping',
            old_name='original_url',
            new_name='originalUrl',
        ),
        migrations.AddField(
            model_name='linkmapping',
            name='lastRedirect',
            field=models.DateTimeField(null=True, verbose_name='time of last redirection'),
        ),
        migrations.AddField(
            model_name='linkmapping',
            name='redirectCount',
            field=models.IntegerField(default=0),
        ),
    ]
