# Generated by Django 5.1 on 2024-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_creation_date_linkmapping_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkmapping',
            name='hash',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
