# Generated by Django 5.1 on 2024-08-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_linkmapping_id_alter_linkmapping_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmapping',
            old_name='hash',
            new_name='shortcode',
        ),
    ]
